AUGMENTATION: True
IMAGE_SIZE : [224,224,3]
BATCH_SZE: 16
INCLUDE_TOP: False # WILL NOT TRAIN THE ENTIRE NETWORK
EPOCHS: 5
CLASSES: 5
WEIGHTS: imagenet
LEARNING_RATE: 0.01
PATIENCE: 5
MONITOR: "val_loss"